import { execFileSync } from "node:child_process";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = resolve(root, "schemas");
const outputDir = resolve(root, "packages/typescript/src/generated");
const rustOutput = resolve(root, "crates/sol-ledger-schema/src/generated.rs");
const schemas = [
  ["artifact-ref.schema.json", "ArtifactRef", "artifact-ref.ts"],
  ["event-envelope.schema.json", "EventEnvelope", "event-envelope.ts"],
  ["provenance-edge.schema.json", "ProvenanceEdge", "provenance-edge.ts"],
  ["security-policy.schema.json", "SecurityPolicy", "security-policy.ts"],
];
const expectedSchemas = schemas.map(([file]) => file).sort();
const actualSchemas = (await readdir(schemaDir))
  .filter((file) => file.endsWith(".schema.json"))
  .sort();
if (JSON.stringify(actualSchemas) !== JSON.stringify(expectedSchemas)) {
  throw new Error(
    `schema generator coverage mismatch: expected ${expectedSchemas.join(", ")}; found ${actualSchemas.join(", ")}`,
  );
}

const expectedOutputs = new Set([...schemas.map(([, , output]) => output), "index.ts"]);
const checkMode = process.argv.includes("--check");
const snapshot = async () => {
  const entries = new Map();
  for (const file of [...expectedOutputs].sort()) {
    entries.set(file, await readFile(resolve(outputDir, file), "utf8").catch(() => null));
  }
  entries.set("generated.rs", await readFile(rustOutput, "utf8").catch(() => null));
  return entries;
};
const before = checkMode ? await snapshot() : null;

const securitySchema = JSON.parse(
  await readFile(resolve(schemaDir, "security-policy.schema.json"), "utf8"),
);

await mkdir(outputDir, { recursive: true });
const unexpectedOutputs = (await readdir(outputDir)).filter(
  (file) => file.endsWith(".ts") && !expectedOutputs.has(file),
);
if (checkMode && unexpectedOutputs.length > 0) {
  throw new Error(`unexpected generated types: ${unexpectedOutputs.sort().join(", ")}`);
}
for (const file of unexpectedOutputs) {
  if (!checkMode) {
    await rm(resolve(outputDir, file));
  }
}
for (const [input, typeName, output] of schemas) {
  const schema = JSON.parse(await readFile(resolve(schemaDir, input), "utf8"));
  schema.title = typeName;
  // Conditional validation is enforced by the runtime validators and is not
  // representable as a sound structural TypeScript type.
  if (schema.allOf?.every((entry) => entry.if)) {
    delete schema.allOf;
  }
  // Resolve the protocol's only external reference from the checked-in source.
  // Generation never fetches schemas over the network.
  if (input === "event-envelope.schema.json") {
    securitySchema.title = "SecurityPolicy";
    delete securitySchema.allOf;
    schema.properties.security = securitySchema;
  }
  const source = await compile(schema, typeName, {
    bannerComment:
      "/* Generated from schemas/*.schema.json by pnpm generate. Do not edit. */",
    cwd: schemaDir,
    format: true,
    unknownAny: true,
  });
  if (/\bany\b/.test(source)) {
    throw new Error(`${output} contains an explicit any type`);
  }
  await writeFile(resolve(outputDir, output), source);
}

await writeFile(
  resolve(outputDir, "index.ts"),
  `/* Generated by pnpm generate. Do not edit. */
export type { ArtifactRef } from "./artifact-ref.js";
export type { EventEnvelope } from "./event-envelope.js";
export type { ProvenanceEdge } from "./provenance-edge.js";
export type { SecurityPolicy } from "./security-policy.js";
`,
);

// The generator is a crate example, so replace the previous generated module
// with a compilable placeholder before Cargo builds the example.
await writeFile(
  rustOutput,
  "// Generated from schemas/*.schema.json by pnpm generate. Do not edit.\n",
);
execFileSync(
  "cargo",
  ["run", "--quiet", "-p", "sol-ledger-schema", "--example", "generate-types"],
  { cwd: root, stdio: "inherit" },
);

if (before) {
  const after = await snapshot();
  const changed = [...after].flatMap(([file, source]) =>
    source === before.get(file) ? [] : [file],
  );
  if (changed.length > 0) {
    throw new Error(`generated types were stale: ${changed.join(", ")}`);
  }
}
