import { execFileSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = resolve(root, "schemas");
const outputDir = resolve(root, "packages/typescript/src/generated");
const rustOutput = resolve(root, "crates/sol-ledger-schema/src/generated.rs");
const schemas = [
  ["artifact-ref.schema.json", "ArtifactRef", "artifact-ref.ts"],
  ["event-envelope.schema.json", "EventEnvelope", "event-envelope.ts"],
  ["provenance-edge.schema.json", "ProvenanceEdge", "provenance-edge.ts"],
  ["security-policy.schema.json", "SecurityPolicy", "security-policy.ts"],
];
const expectedSchemas = schemas.map(([file]) => file).sort();
const actualSchemas = (await readdir(schemaDir))
  .filter((file) => file.endsWith(".schema.json"))
  .sort();
if (JSON.stringify(actualSchemas) !== JSON.stringify(expectedSchemas)) {
  throw new Error(
    `schema generator coverage mismatch: expected ${expectedSchemas.join(", ")}; found ${actualSchemas.join(", ")}`,
  );
}

const expectedOutputs = new Set([...schemas.map(([, , output]) => output), "index.ts"]);
const checkMode = process.argv.includes("--check");
const snapshot = async (typescriptDirectory, rustPath) => {
  const entries = new Map();
  for (const file of [...expectedOutputs].sort()) {
    entries.set(file, await readFile(resolve(typescriptDirectory, file), "utf8").catch(() => null));
  }
  entries.set("generated.rs", await readFile(rustPath, "utf8").catch(() => null));
  return entries;
};
const before = checkMode ? await snapshot(outputDir, rustOutput) : null;

const securitySchema = JSON.parse(
  await readFile(resolve(schemaDir, "security-policy.schema.json"), "utf8"),
);

if (!checkMode) await mkdir(outputDir, { recursive: true });
const existingOutputs = await readdir(outputDir).catch((error) => {
  if (error.code === "ENOENT") return [];
  throw error;
});
const unexpectedOutputs = existingOutputs.filter(
  (file) => file.endsWith(".ts") && !expectedOutputs.has(file),
);
if (checkMode && unexpectedOutputs.length > 0) {
  throw new Error(`unexpected generated types: ${unexpectedOutputs.sort().join(", ")}`);
}
await mkdir(resolve(root, ".tmp"), { recursive: true });
const temporaryRoot = await mkdtemp(resolve(root, ".tmp/generate-types-"));
const temporaryTypes = resolve(temporaryRoot, "typescript");
const temporaryRust = resolve(temporaryRoot, "generated.rs");
await mkdir(temporaryTypes, { recursive: true });
try {
  for (const [input, typeName, output] of schemas) {
    const schema = JSON.parse(await readFile(resolve(schemaDir, input), "utf8"));
    schema.title = typeName;
    // Conditional validation is enforced by the runtime validators and is not
    // representable as a sound structural TypeScript type.
    if (schema.allOf?.every((entry) => entry.if)) {
      delete schema.allOf;
    }
    // Resolve the protocol's only external reference from the checked-in source.
    // Generation never fetches schemas over the network.
    if (input === "event-envelope.schema.json") {
      securitySchema.title = "SecurityPolicy";
      delete securitySchema.allOf;
      schema.properties.security = securitySchema;
    }
    const source = await compile(schema, typeName, {
      bannerComment:
        "/* Generated from schemas/*.schema.json by pnpm generate. Do not edit. */",
      cwd: schemaDir,
      format: true,
      unknownAny: true,
    });
    if (/\bany\b/.test(source)) {
      throw new Error(`${output} contains an explicit any type`);
    }
    await writeFile(resolve(temporaryTypes, output), source);
  }

  await writeFile(
    resolve(temporaryTypes, "index.ts"),
    `/* Generated by pnpm generate. Do not edit. */
export type { ArtifactRef } from "./artifact-ref.js";
export type { EventEnvelope } from "./event-envelope.js";
export type { ProvenanceEdge } from "./provenance-edge.js";
export type { SecurityPolicy } from "./security-policy.js";
`,
  );

  execFileSync(
    "cargo",
    ["run", "--quiet", "-p", "sol-ledger-schema-generator"],
    { cwd: root, stdio: "inherit", env: { ...process.env, SOL_LEDGER_GENERATED_RS_OUT: temporaryRust } },
  );

  if (before) {
    const after = await snapshot(temporaryTypes, temporaryRust);
    const changed = [...after].flatMap(([file, source]) =>
      source === before.get(file) ? [] : [file],
    );
    if (changed.length > 0) {
      throw new Error(`generated types were stale: ${changed.join(", ")}`);
    }
  } else {
    const backupTypes = resolve(temporaryRoot, "backup-types");
    const backupRust = resolve(temporaryRoot, "backup-generated.rs");
    await mkdir(backupTypes);
    const moved = [];
    const published = [];
    const backup = async (source, destination) => {
      try {
        await rename(source, destination);
        moved.push([source, destination]);
      } catch (error) {
        if (error.code !== "ENOENT") throw error;
      }
    };
    try {
      for (const file of [...expectedOutputs, ...unexpectedOutputs]) {
        await backup(resolve(outputDir, file), resolve(backupTypes, file));
      }
      await backup(rustOutput, backupRust);
      for (const file of expectedOutputs) {
        const destination = resolve(outputDir, file);
        await rename(resolve(temporaryTypes, file), destination);
        published.push(destination);
      }
      await rename(temporaryRust, rustOutput);
      published.push(rustOutput);
    } catch (error) {
      for (const path of published.reverse()) await rm(path, { force: true });
      for (const [source, destination] of moved.reverse()) await rename(destination, source);
      throw error;
    }
  }
} finally {
  await rm(temporaryRoot, { recursive: true, force: true });
}
